<?php
/**
 * Vivora Healthcare - one-time web installer.
 *
 * 1. Tests the MySQL connection with the details you enter.
 * 2. Writes config.php on the server (config.php is NOT stored in Git).
 * 3. Creates all tables and seeds categories, starter products and the admin user.
 *
 * Once an admin user exists the installer locks itself.
 */

declare(strict_types=1);

define('APP_ROOT', __DIR__);
require __DIR__ . '/includes/functions.php';
require __DIR__ . '/includes/schema.php';

ini_set('display_errors', '0');
header('X-Robots-Tag: noindex, nofollow');

$configFile = __DIR__ . '/config.php';
$errors = [];
$log = [];
$done = false;

/** Is the site already installed (config present and an admin exists)? */
function already_installed(string $configFile): bool
{
    if (!is_file($configFile)) {
        return false;
    }
    try {
        require_once $configFile;
        $pdo = new PDO('mysql:host=' . DB_HOST . ';dbname=' . DB_NAME . ';charset=utf8mb4', DB_USER, DB_PASS, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
        return (int) $pdo->query('SELECT COUNT(*) FROM admins')->fetchColumn() > 0;
    } catch (Throwable $e) {
        return false;
    }
}

$installed = already_installed($configFile);

$form = [
    'db_host' => 'localhost',
    'db_name' => 'u734104989_mshealthcares',
    'db_user' => 'u734104989_mshealthcares',
    'db_pass' => '',
];

if (!$installed && ($_SERVER['REQUEST_METHOD'] ?? '') === 'POST') {
    foreach ($form as $k => $_) {
        $form[$k] = trim((string) ($_POST[$k] ?? ''));
    }
    $form['db_pass'] = (string) ($_POST['db_pass'] ?? '');

    // Hostinger databases are always reached via "localhost" from your website.
    // Remote hosts are refused so nobody can point a fresh install at their own server.
    if (!in_array(strtolower($form['db_host']), ['localhost', '127.0.0.1'], true)) {
        $errors[] = 'Database host must be "localhost" (this is what Hostinger uses for websites on the same account).';
    }
    if ($form['db_name'] === '' || $form['db_user'] === '') {
        $errors[] = 'Database name and username are required.';
    }

    if (!$errors) {
        try {
            $pdo = new PDO(
                'mysql:host=' . $form['db_host'] . ';dbname=' . $form['db_name'] . ';charset=utf8mb4',
                $form['db_user'],
                $form['db_pass'],
                [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
            );
        } catch (Throwable $e) {
            $errors[] = 'Could not connect to MySQL: ' . $e->getMessage();
        }
    }

    if (!$errors) {
        $config = "<?php\n"
            . "// Generated by install.php on " . date('Y-m-d H:i') . ". Keep this file private - it is excluded from Git.\n"
            . "define('DB_HOST', " . var_export($form['db_host'], true) . ");\n"
            . "define('DB_NAME', " . var_export($form['db_name'], true) . ");\n"
            . "define('DB_USER', " . var_export($form['db_user'], true) . ");\n"
            . "define('DB_PASS', " . var_export($form['db_pass'], true) . ");\n"
            . "define('DB_PORT', '');\n"
            . "define('APP_DEBUG', false);\n";
        if (@file_put_contents($configFile, $config) === false) {
            $errors[] = 'Could not write config.php. Create it manually from config.sample.php using Hostinger File Manager, then reload this page.';
        } else {
            @chmod($configFile, 0640);
        }
    }

    if (!$errors) {
        try {
            $log = vivora_install($pdo, 'admin', 'admin123');
            $done = true;
        } catch (Throwable $e) {
            $errors[] = 'Installation failed: ' . $e->getMessage();
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex, nofollow">
    <title>Install · Vivora Healthcare</title>
    <link rel="icon" href="assets/images/favicon.png">
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/vendors/css/vendors.min.css">
    <link rel="stylesheet" href="assets/css/theme.min.css">
</head>
<body class="bg-light">
<main class="container py-5" style="max-width:640px">
    <div class="text-center mb-4">
        <img src="assets/images/logo-full.png" alt="Vivora Healthcare" style="max-width:280px" class="img-fluid">
    </div>
    <div class="card">
        <div class="card-body p-4 p-sm-5">
            <?php if ($installed): ?>
                <h4 class="fw-bold mb-3"><i class="feather-check-circle text-success me-2"></i>Already installed</h4>
                <p class="text-muted">Vivora Healthcare is installed and the installer is locked. You can delete <code>install.php</code> from the server.</p>
                <a href="admin/login.php" class="btn btn-primary">Go to dashboard login</a>
            <?php elseif ($done): ?>
                <h4 class="fw-bold mb-3"><i class="feather-check-circle text-success me-2"></i>Installation complete</h4>
                <ul class="mb-4">
                    <?php foreach ($log as $line): ?><li><?= e($line) ?></li><?php endforeach; ?>
                </ul>
                <div class="alert alert-warning">
                    Log in with <strong>admin</strong> / <strong>admin123</strong>, then change the password under
                    <em>My Profile</em>. For extra safety delete <code>install.php</code> from the server.
                </div>
                <a href="admin/login.php" class="btn btn-primary">Go to dashboard login</a>
            <?php else: ?>
                <h4 class="fw-bold mb-1">Dashboard installer</h4>
                <p class="text-muted mb-4">Enter your Hostinger MySQL details (hPanel → Databases → Management).</p>
                <?php foreach ($errors as $err): ?>
                    <div class="alert alert-danger"><?= e($err) ?></div>
                <?php endforeach; ?>
                <?php if (!is_writable(__DIR__)): ?>
                    <div class="alert alert-warning">The folder is not writable, so <code>config.php</code> cannot be created automatically. Create it from <code>config.sample.php</code> in File Manager.</div>
                <?php endif; ?>
                <form method="post" autocomplete="off">
                    <div class="mb-3">
                        <label class="form-label">Database host</label>
                        <input class="form-control" name="db_host" value="<?= e($form['db_host']) ?>" required>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Database name</label>
                        <input class="form-control" name="db_name" value="<?= e($form['db_name']) ?>" required>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Database username</label>
                        <input class="form-control" name="db_user" value="<?= e($form['db_user']) ?>" required>
                    </div>
                    <div class="mb-4">
                        <label class="form-label">Database password</label>
                        <input type="password" class="form-control" name="db_pass" required>
                    </div>
                    <button class="btn btn-primary w-100 btn-lg">Install dashboard</button>
                </form>
            <?php endif; ?>
        </div>
    </div>
</main>
</body>
</html>
